config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
	get 'about' => 'pages#about'
	mount Attachinary::Engine => "/attachinary"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	has_attachment  :image, accept: [:jpg, :jpeg, :png, :gif]
	validates :image, presence: true
 # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
		devise_parameter_sanitizer.for(:sign_up) << :last_name
		devise_parameter_sanitizer.for(:account_update) << :first_name
		devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def about
	end

	def contact
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
  before_filter :check_configuration

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
		@page_title = "Pins"
  end

  def show
		@page_title = "Pin nr. #{@pin.id}"
  end

  def new
    @pin = current_user.pins.build
		@page_title = "New pin"
  end

  def edit
		@page_title = "Edit pin"
  end

  def create
    @pin = current_user.pins.build(pin_params)
		@page_title = "Create new pin"

      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render :new
      end
  end

  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        frender :edit
      end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  def check_configuration
    redirect_to root_path, notice: 'Cloudinary configuration missing !' if Cloudinary.config.api_key.blank?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

		def correct_user
			@pin = current_user.pins.find_by(id: params[:id])
			redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end

		def set_title 
			@page_title
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pinterest', root_path, class: "navbar-brand" %>
    </div>


		<div class="collapse navbar-collapse navbar-ex1-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        		<li><%= link_to 'Home', root_path %></li>
				    <li><%= link_to 'About', about_path %></li>
						<% if user_signed_in? %>
              <li><%= link_to new_pin_path, class: "pin-new" do %>
              <span class="glyphicon glyphicon-plus-sign pin-new"></span> New Pin
              <% end %></li>
							<li><%= link_to 'Account Settings', edit_user_registration_path %></li>
							<li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li><%= link_to 'Sign in', new_user_session_path %></li>
						<% end %>
      </ul>
  	</div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<%= cloudinary_js_config %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">	
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-info") %>
				<% end %>
				<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app !</h1>
	<% if user_signed_in? %>
		# do something
	<% else %>
	<p>
		<%= link_to 'Log in', new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
	<% end %>
</div>

app/views/pages/about.html.erb
<div class="jumbotron center">
	<h1>Here you can read more about Pinterest</h1>
	<% if user_signed_in? %>
		# do something
	<% else %>
	<p>
		<%= link_to 'Log in', new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
				<% if @pin.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

						<ul>
						<% @pin.errors.full_messages.each do |message| %>
						  <li><%= message %></li>
						<% end %>
						</ul>
					</div>
				<% end %>

				<div class="form-group">
					<%= f.label :image %><br>
					<%= f.attachinary_file_field :image, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :description %><br>
					<%= f.text_field :description, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.submit class: "btn btn-primary" %>
				</div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home.html.erb' unless user_signed_in?%>
<div class="row-fluid">
	<div class="col-md-12">
		<div id="pins" class="transitions-enabled center">
			<% @pins.each do |pin| %>
				<div class="box panel panel-default">
				  	<% if pin.image? %>
						<%= link_to (cl_image_tag(pin.image.path, {  crop: :fit})), pin %>
					<% end %>
					<div class="panel-body">
					    <%= pin.description %>
						<% if pin.user.first_name && pin.user.last_name %><br>
							<strong><%= pin.user.first_name %> <%= pin.user.last_name %></strong>
							<% else %>
							<strong><%= pin.user.email %></strong>
						<% end %>
					</div>
					<% if pin.user == current_user %>
					    <div class="panel-footer">
							<%= link_to edit_pin_path(pin) do %>
								<span class="glyphicon glyphicon-edit"></span> Edit
							<% end %> | 
						    <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' }  do %>
								<span class="glyphicon glyphicon-trash"></span> Delete
						    <% end %>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
		<div class="center"><%= will_paginate @pins, renderer: BootstrapPagination::Rails %></div>
	</div>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h2><%= @page_title %></h2></div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
	<%= link_to pins_path do %>
		<span class="glyphicon glyphicon-arrow-left"></span> Back
	<% end %>
<div class="row-fluid">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
					<% if @pin.image? %>
							<%= cl_image_tag(@pin.image.path, { size: '700x550', crop: :fit }) %>
					<% end %>
			</div>
			<div class="panel-body">
				<p><%= @pin.description %></p>
				<% if @pin.user.first_name && @pin.user.last_name %>
				<p><strong><%= @pin.user.first_name %> <%= @pin.user.last_name %></strong></p>
				<% else %>
				<p><strong><%= @pin.user.email %></strong></p>
				<% end %>
			</div>
			<div class="panel-footer">
				<% if @pin.user == current_user %>
					<%= link_to edit_pin_path(@pin) do %>
						<span class="glyphicon glyphicon-edit"></span> Edit
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>